Fixed duplicate run when use multiple instance
rayriffy/elysia-rate-limit pull request #43
Opened 2024-05-03 12:30 UTC by armada45-pixel

Fix https://github.com/rayriffy/elysia-rate-limit/issues/42

change type inject Server return value to `server or null`
because typeof elysia.server is `server or null`
https://github.com/rayriffy/elysia-rate-limit/compare/main...armada45-pixel:dev-arm-1?expand=1#diff-416aa897f3ece839c33af4d41fc86ac3e601372ce3f32cbf0bba7d1789dcd37f
```ts
let serverInstance: Server
const app = new Elysia()
serverInstance = app.server as Server <= fix type required
```

2024-05-04 20:02 UTC, rayriffy requested changes
This change failed example `basic.ts`, and `multiInstance.ts`. Please fix those and do a self-test before request for re-review.

Also, please rename your pull request properly.

2024-05-19 09:46 UTC, rayriffy approved these changes

2024-05-19 09:52 UTC, rayriffy requested changes
Just did a retest, but unfortunately `./example/multiInstance.ts` example swagger does not work, please look into that.

2024-05-19 12:32 UTC, armada45-pixel commented
I don't know why swagger not working, But after [update dependencies](https://github.com/rayriffy/elysia-rate-limit/pull/43/commits/aec14648008202af897ead2756231a018935f555) everything look fine.

2024-05-21 15:18 UTC, rayriffy approved these changes
Thanks for contributing. When creating the next contribution, please always create a new branch to prevent mixed up with unrelated commit from last contribution.

2024-05-22 08:19 UTC, armada45-pixel commented
> Thanks for contributing. When creating the next contribution, please always create a new branch to prevent mixed up with unrelated commit from last contribution.

Sorry, I'dont know this gonna happen.

2024-05-22 08:30 UTC, armada45-pixel commented on src/services/plugin.ts
> +      console.log('onBeforeHandle')
Why use `console.log` instead of `logger`

2024-05-22 10:39 UTC, merged